### ISSUE TITLE
Remote Host Idenification has changed

### ISSUE THREAD

**Issue by bgreis** [4ahmns2122-VR/VRProjekt2122-bgreis#2]
<img width="1280" alt="Screenshot 2022-01-20 at 13 33 47" src="https://user-images.githubusercontent.com/72389948/150339868-3b8202f4-0946-4a17-97eb-bc8cbbca8c44.png">

**Comment by smeerws** [comment]
Mehrere Varianten: 
1) einfach die known_hosts löschen (über Konsole oder Explorer) Wenn ein Server nächstes Mal was braucht wird diese wieder angelegt. 

2)Da muss dann der offending ECDSA key gelöscht werden, ich vermute sowas in der Richtung evt. Zeile 4
github.com dann ganz viele Zahlen (Hash) und da muss auch  ECDSA dabei stehen
siehe
https://kinsta.com/de/wissensdatenbank/warning-remote-host-identification-has-changed/
D.h. mit einem Texteditor evt. Nano einem Texteditor deiner Wahl /Users/benediktgreisberger/.ssh/known-hosts öffnen und den betreffenden Eintrag löschen 

3) https://gist.github.com/ataliba/2396042: ssh-keygen -R {server.name.com}

**Comment by bgreis** [comment]
Habe die erste Variante ausprobiert und jetzt hab ich dieses Problem :
<img width="954" alt="Screenshot 2022-01-23 at 11 44 59" src="https://user-images.githubusercontent.com/72389948/150674928-b0553a83-d720-404e-b101-8e2086a2ac54.png">

**Comment by smeerws** [comment]
Irgendwie scheint der Key Online nicht mit dem Key lokal zuammenzustimmen!

Führe mal folgendes aus:
ssh -vT git@github.com

Da muss dann unter Offering public key der Pfad zu deinem Key und der Fingerprint angegeben sein und dieser muss übereinstimmen mit Server Accepts key wieder Pfad zu deinem Key und der Fingerprint. 
Unten muss dann noch dein Username sein Hi bgreis! You've ...

Evt finden wir so den Fehler!

https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

**Comment by bgreis** [comment]
in .ssh beide remotehosts gelöscht
key aus der KeyChain Access gelöscht und
"ssh -vT git@github.com" eingeben
und dann "yes"

dann neu pullen & mergen
